global:
  scrape_interval: 5s   # how often to scrape metrics

scrape_configs:
  # =====================
  # Product Service metrics
  # =====================
#  commented as metrics and traces are being scraped by otel collector via push mechanism
#  - job_name: 'product-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['product-microservice:8080']
#
#  # =====================
#  # Order Service metrics
#  # =====================
#  commented as metrics and traces are being scraped by otel collector via push mechanism
#  - job_name: 'order-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['order-microservice:8080']

  # =====================
  # OpenTelemetry Collector metrics
  # =====================
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
